apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellofe
  labels:
    app: hellofe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellofe
  template:
    metadata:
      labels:
        app: hellofe
    spec:
      containers:
      - name: hellofe
        image: jfrankenbach/angular_frontend:latest
        ports:
        - containerPort: 4200
