apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hellofe
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: hellofe
          servicePort: 4200
